language: node_js
node_js:
  - "7.2.1"

cache:
  yarn: true

script:
  - npm run lint
  - npm run test:cover
  - npm run codacy:coverage

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"