export const LOAD_RECIPES_SUCCESS = "LOAD_RECIPES_SUCCESS";
export const LOAD_RECIPES_FAILURE = "LOAD_RECIPES_FAILURE";
export const LOAD_INGREDIENT_LIST_SUCCESS = "LOAD_INGREDIENT_LIST_SUCCESS";
export const LOAD_INGREDIENT_LIST_FAILURE = "LOAD_INGREDIENT_LIST_FAILURE";