export const LOAD_RECIPES_SUCCESS = "LOAD_RECIPES_SUCCESS";
export const UPDATE_RECIPE_SUCCESS = "UPDATE_RECIPE_SUCCESS";
export const LOAD_RECIPES_FAILURE = "LOAD_RECIPES_FAILURE";
export const LOAD_INGREDIENT_LIST_SUCCESS = "LOAD_INGREDIENT_LIST_SUCCESS";
export const LOAD_INGREDIENT_LIST_FAILURE = "LOAD_INGREDIENT_LIST_FAILURE";

export const XHR_CALL_START = "XHR_CALL_START";
export const XHR_CALL_FAILURE = "XHR_CALL_FAILURE";